services:

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - PORT=${FRONT_PORT}
      - REACT_APP_BACK_PORT=${BACK_PORT}
      - REACT_APP_BACK_DOMAIN=${BACK_DOMAIN}
      - REACT_APP_BACK_URI=${BACK_URI}
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env
      - .env
    ports:
      - ${BACK_PORT}:${BACK_PORT}
      - 9229:9229
      - "5002:5002"
      - "6881-6889:6881-6889"
      - "6881-6889:6881-6889/udp"
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    build:
      context: ./mariadb.config
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    env_file:
      - ./backend/.env
    healthcheck:
      test: "mariadb -u$$MARIADB_USER -p$$MARIADB_ROOT_PASSWORD -e 'SELECT 1;'"
      interval: 2s
      timeout: 5s
      retries: 10
